### ISSUE TITLE
Git diff failing - classic non-yaml PR pipeline

### ISSUE THREAD

**Issue by ColinKrist** [microsoft/OMEX-Azure-DevOps-Extensions#61]
## Summary

This line is failing on my repo: 
https://github.com/microsoft/OMEX-Azure-DevOps-Extensions/blob/7bdbb325db12c82e761991c4fa4d5a179e763c3e/PipelinesTasks/PRMetrics/buildAndReleaseTask/src/git/gitInvoker.ts#L33

This is a classic release pipeline with the OAuth token checkbox checked:
![image](https://user-images.githubusercontent.com/27971797/115257862-1a629780-a0f6-11eb-8014-6bb5fb70cd2a.png)

I have another classic release pipeline that works a-ok, so I'm a bit stumped. The only guess I have is that this one uses 'develop' instead of 'development'

screenshot of pipeline run:
![image](https://user-images.githubusercontent.com/27971797/115257252-82fd4480-a0f5-11eb-8bd2-32b5021efdad.png)

## Reproduction Steps

Open PR into 'develop' PR metrics step runs and then fails with this.

**Comment by muiriswoulfe** [comment]
Hi @ColinKrist. I believe the issue is likely that you have "shallow fetch" turned on for your pipeline.

In your pipeline definition, navigate to "Get sources". At the bottom, there will be a checkbox for "Shallow fetch". If this is on, it's likely that the task won't work. Let me know if it continues to fail and I can investigate further.

In reality, it's possible to leave this on and set the value appropriately deep to allow the task to run, but this depth will depend on the layout of your repo branches so the easiest option – at least initially – is to just switch this off.

By the way, I'm currently working on adding a check for this, which will provide a more useful error message in the case of failures, although it'll likely be a little while still before I am able to get this out. It won't really benefit you here as it will essentially just check for the failure you're seeing and translate it into something more comprehensible.

**Comment by ColinKrist** [comment]
this did the trick - looking forward to the enhancement too that'll be helpful when we have other engineers troubleshoot as we adopt this into our other pipelines. Thanks!!
